name: Packaging
on:
  workflow_dispatch:
  push:
    branches:
      - package
    tags:
      - '*'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-20.04
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 16
        include:
          - os: windows-latest
            node: 16
            host: x86
            target: x86
          # This is a self-hosted runner, github doesn't have this architecture yet.
#          - os: macos-m1
#            node: 16
#            host: arm64
#            target: arm64
    name: ${{ matrix.os }} (node=${{ matrix.node }}, host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - name: association
        if: contains(matrix.os, 'windows')
        run: |
          ls
          ls "c:\\"
          ls "c:\\Program Files"
          ls "c:\\Program Files/Git"
          ls "c:\\Program Files/Git/bin"
          cmd /c assoc .sh=bashscript
          cmd /c ftype bashscript="%ProgramFiles%\Git\bin\bash.exe" "%1"
          cmd /c ftype

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: check bash
        run: yarn run check:bash:ci

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Add yarn (self-hosted)
        if: matrix.os == 'macos-m1'
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --network-timeout 300000

      - name: Hooks and crooks
        run: yarn run setup
        env:
          RUN_OS: ${{ matrix.os }}
          RUN_ARCH: ${{ matrix.target }}

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Package
        # github endpoints hang up quite a bit, add one retry.
        run: yarn run electron:ci || yarn run electron:ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEBUG: electron-builder
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
